### PR TITLE
The first Social Media APIs !

### PR DESCRIPTION
**Pull request by bobvdvelde**
This update includes:

Text Interfaces! These were required to make adding apps for social media APIs and credentials to use with them.

ES 5 compatible schema(!) Which solves bugs around too many fields errors (standard limitation of 1000 unique fields). In addition, the 'id' field was sensitive to the order of scrapers. If twitter, which has integer IDs, was run before YouTube (which has string IDs), the latter would be rejected (ACK!). 

The pospone method now works as intended!

### CODE REVIEW

**Comment by damian0604** [comment]
Great!!
It's not completely clear to me how the clients are to be used, could you give a minimal example for how the clients are typically to be used?
Thanks!

**Comment by bobvdvelde** [comment]
@damian0604 the argument for run functions is `app`, not `appname`. We may want to change this for consistency.

**Comment by damian0604** [comment]
I see. Then it should be fine for now! I'll update the docs and continue testing.

**Comment by bobvdvelde** [comment]
Well, you are pretty right that it's weird that the argument is different for different functions. I'm reluctant to change it as @theoaraujo is using it in production, but it would definitely make more sense.

**Comment by damian0604** [comment]
OK. I'll make an issue so that we can fix this later once we're sure we don't break production code.

Tested Twitter now, that works, but I have a problem with Youtube. Authentication seems to work, but bulk insert does not:

```
In [24]: myinca.clients.youtube_videos_search(q='test')
INFO:INCA.core.client_class:UPDATED credentials damian for default
INFO:INCA.core.client_class:Starting client
---------------------------------------------------------------------------
BulkIndexError                            Traceback (most recent call last)
<ipython-input-24-4c883672834e> in <module>()
----> 1 myinca.clients.youtube_videos_search(q='test')

/Users/damian/inca/inca.py in endpoint(*args, **kwargs)
    173                     else:
    174                         def endpoint(*args, **kwargs):
--> 175                             return method(*args, **kwargs)
    176                     return endpoint
    177 

/Users/damian/inca/core/document_class.py in runwrap(self, action, *args, **kwargs)
     37         '''
     38         if action == 'run':
---> 39             return self.run(*args, **kwargs)
     40 
     41         if action == 'delay':

/Users/damian/inca/core/client_class.py in run(self, app, *args, **kwargs)
    207                     doc = self._add_metadata(doc)
    208                     self._verify(doc)
--> 209                 self._save_documents(docs)
    210 
    211         else:

/Users/damian/inca/core/document_class.py in _save_documents(self, documents, forced)
     98             self._verify(document)
     99 
--> 100         insert_documents(documents)
    101 
    102     def _update_document(self, new_document_body):

/Users/damian/inca/core/database.py in insert_documents(documents, identifiers)
    235         doc['_type']  = doc['doctype']
    236     # Insert documents
--> 237     logger.debug(helpers.bulk(client, documents))
    238     return [doc.get('_id','random') for doc in documents]
    239 

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/elasticsearch/helpers/__init__.py in bulk(client, actions, stats_only, **kwargs)
    193     errors = []
    194 
--> 195     for ok, item in streaming_bulk(client, actions, **kwargs):
    196         # go through request-reponse pairs and detect failures
    197         if not ok:

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/elasticsearch/helpers/__init__.py in streaming_bulk(client, actions, chunk_size, max_chunk_bytes, raise_on_error, expand_action_callback, raise_on_exception, **kwargs)
    161 
    162     for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
--> 163         for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
    164             yield result
    165 

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/elasticsearch/helpers/__init__.py in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs)
    133 
    134     if errors:
--> 135         raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
    136 
    137 def streaming_bulk(client, actions, chunk_size=500, max_chunk_bytes=100 * 1024 * 1024,

BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_id': 'NRvbtUwiyoY', 'error': {'caused_by': {'type': 'number_format_exception', 'reason': 'For input string: "NRvbtUwiyoY"'}, 'type': 'mapper_parsing_exception', 'reason': 'failed to parse [id]'}, '_index': 'inca', '_type': 'youtube_video', 'status': 400}}])

In [25]: 
```

**Comment by damian0604** [comment]
Ah, I see now:
> ES 5 compatible schema(!) Which solves bugs around too many fields errors (standard limitation of 1000 unique fields). In addition, the 'id' field was sensitive to the order of scrapers. If twitter, which has integer IDs, was run before YouTube (which has string IDs), the latter would be rejected (ACK!).
So it was because my database still used the old schema.
Thus, everything ok!

**Pull request merged**
