### PR TITLE
Updaterequirements

### PR DESCRIPTION
**Pull request by damian0604**
On a fresh Linux VM,  running `sudo  setup_fresh_ubuntu_machine.sh ` and then installing the Requirements should now install everything that's needed (except Elasticsearch itself), using more recent versions to of some core packages to get rid of deprecation warnings

### CODE REVIEW

**Comment by FeLoe** [comment]
I tried it in a venv on a Mac - I had to comment out 'inca' and 'nl-core-news-sm' in the Requirements to get it to work - do we need them? Another thing: I get the 'no elasticsearch' warning regarding APIs in total 8 times each when importing Inca and when setting up an instance of Inca(). Any idea why that pops up so many times? Otherwise everything works fine.

**Comment by damian0604** [comment]
Thanks for having a look! I removed the indeed circular `inca` entry.
The NL-core... thing is needed for the NER-processor, that's why. Is it that pip on mac cannot handle such requirements (with an URL) in general or is it sth else?
About the multiple warnings: it's because when populating the inca class,  several functions try to import the module that connects to ES. we can fix that another time....

**Comment by FeLoe** [comment]
Somehow the NL-core got installed anyway (through some of the other requirements) - just pip installing it does not work...

**Comment by damian0604** [comment]
hmm.... can we merge (i.e., you approve ;-) ) anyway because it seems necessary on unix which is our prime target?

**Pull request merged**
