### PR TITLE
fix for language issues with lda

### PR DESCRIPTION
**Pull request by FeLoe**
At least temporary fix (language can now be inserted as argument) - SnowballStemmer instead of PorterStemmer for other languages but no equivalent for lemmatizer...

### CODE REVIEW

**Comment by damian0604** [comment]
I thought it's a better idea to not hard-code the language but rather read it from the settings.cfg file. See latest commit. What do you think, @FeLoe ?

**Comment by FeLoe** [comment]
Yes, I think it is a good idea - I just had to change the name of the settings file, now everything is working!

**Comment by damian0604** [comment]
Thanks!
I'll revert that though, because default_settings is just an example. When installing INCA, default_settings.cfg is automatically copied to settings.cfg.  So only people with older installations (like us) have to change settings.cfg by hand. This is because settings.cfg can also contain login info and so on, therefore it's not supposed to be on github.

**Comment by FeLoe** [comment]
Ah ok - its just that I got an error when trying the code - maybe we need an explanation for this somewhere?

**Comment by damian0604** [comment]
There is, in fact, an issue for that:
https://github.com/uvacw/inca/issues/244
It's just that no one has had the time to pick it up (and/or a great idea of how to solve it)

**Comment by damian0604** [comment]
I'm gonna fix #244

**Pull request merged**
