### PR TITLE
Classification analysis class

### PR DESCRIPTION
**Pull request by damian0604**
Hi Bob, could you please check if it works as you expected? Thanks!!

### CODE REVIEW

**Comment by bobvdvelde** [comment]
I'm seeing some problems in the pre-processing stage (unhandled errors about mismatches between x_field and label_field lengths). I'll need to dig a bit deeper to find a root cause and finish the review. I'll try and do this on the 18th of January.

**Comment by damian0604** [comment]
I'm going to look into it.

**Comment by damian0604** [comment]
I already see it: this is because the function retrieves the document from the DB again (see line 121), because after the loop starting in line 94, the generator is exhausted.
Unless the option one-pass=True is specified (and the docs kept in memory), the documents thus are re-retrieved based on their ID, meaning that your data manipulation is gone (changing 10 cases). 

I see that this behavior needs to be handled differently, but do you have a concrete suggestion on what would be the best cause of action, @bobvdvelde ?

**Comment by damian0604** [comment]
(that still doesn't explain why there are exactly 32 extra observations, though)

**Comment by damian0604** [comment]
Hi @bobvdvelde , see my latest commit. I think it should be solved.

**Comment by theoaraujo** [comment]
I ran the same tests as Bob (also with tweets, but with 18K that I had myself in a local version of inca). I'm afraid there's still an error message:

image

Let me know if I'm doing something wrong in the test, as I did not dive too deep in the documentation of the class.

**Comment by damian0604** [comment]
Thanks for testing! Which version of sklearn are you using?

Verstuurd vanaf mijn iPhone

Op 9 feb. 2018 om 12:04 heeft Theo Araujo <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I ran the same tests as Bob (also with tweets, but with 18K that I had myself in a local version of inca). I'm afraid there's still an error message:

[image]<https://user-images.githubusercontent.com/9536412/36024840-4772598c-0d91-11e8-9983-e08c96290687.png>

Let me know if I'm doing something wrong in the test, as I did not dive too deep in the documentation of the class.

**Comment by theoaraujo** [comment]
Hi @damian0604 

I updated scikit-learn using the new requirements file you added. Good news is that the error message now changed... :-)

Let me know if it's something wrong with the test case (I'm using the same code as Bob), or if there's something different I need to do.

Cheers,
Theo

image

**Pull request merged**
